### ISSUE TITLE
Touch to scroll page

### ISSUE THREAD

**Issue by dpierangeli** [OptimiliaStudios/AquileReader#1]
Hello, i used the app to read ebooks and is very good.

I use the reader on a touch device (Surface Go 1).

I'd like to scroll page by using a touch swipe, now i must click in the right/left edge.

**Comment by OptimiliaStudios** [comment]
We are already working on it, next update should have it.

Apart from that did you face any crashes, UI bugs, anything annoying?

**Comment by dpierangeli** [comment]
1) the font chooser combo on the surface go is not usable:

![IMG_20200827_212527.jpg](https://user-images.githubusercontent.com/9047951/91486026-fd016480-e8ab-11ea-9fc6-c79b7b88c725.jpg)

On my laptop is OK.

Do you need some information? (resolution, zoom,...)

2) read aloud crashes the app ( maybe because the system language is Italian).

**Comment by OptimiliaStudios** [comment]
Yes plz, the resolution, zoom % would be helpful.

For #2, can you plz give more details, like the steps you do which results in crash? Language of the book, Speech language selected in app, system language, etc?

**Comment by dpierangeli** [comment]
Surface go 1800x1200 zoom 150%

The read aloud crashes after 2 seconds from activation (no sound).
The system language is Italian, i tried with an English book (Sherlock Holmes) and an Italian book.

I've not found the read aloud language settings.

**Comment by dpierangeli** [comment]
I attach the event viewer log of the error.

[Event Viewer Log.zip](https://github.com/OptimiliaStudios/AquileReader/files/5191000/Event.Viewer.Log.zip)

**Comment by OptimiliaStudios** [comment]
1. Update with support for swipe gesture was released last week, you can try it out.
2. When the app crashes, do you see a window like this or it just closes?
![image](https://user-images.githubusercontent.com/67598009/92850807-7d76a800-f40a-11ea-91d2-0ac36393eee9.png)
3. From the event viewer traces, it looks like the TTS engine itself is crashing "C:\Windows\System32\speech_onecore\engines\tts\MSTTSEngine_OneCore.dll", are you able to use any other TTS app (UWP) on your device? You can try 'ReadAloud' app and see if that works.

**Comment by dpierangeli** [comment]
1- tested and is good ! Thanks
2- it just closes
3- chromium edge read aloud works, the read aloud app crashes.

**Comment by OptimiliaStudios** [comment]
Closing the issue as the crash is due to Windows TTS engine crashing and not due to app bug.
