### ISSUE TITLE
Please add more language support such as Chinese

### ISSUE THREAD

**Issue by SJC08** [OptimiliaStudios/AquileReader#104]

**Comment by OptimiliaStudios** [comment]
We have plans to add more languages in near future and would reach out to for translation help. If interested, please drop an email at optimilia.studios@gmail.com

**Comment by OptimiliaStudios** [comment]
Hi @SJC08,
Aquile Reader is now ready for localization, you can contribute by following the details here - https://github.com/OptimiliaStudios/AquileReader/issues/111

**Comment by OptimiliaStudios** [comment]
Chinese language support has been added to the app.
