### ISSUE TITLE
Suggestions on Repeated Storage in Library and Hyperlink Jump of epub Files

### ISSUE THREAD

**Issue by qtqtEricChiu** [OptimiliaStudios/AquileReader#106]
I am an epub-maker. I noticed that after I opened the same Epub file from the File Explorer many times, many different versions appeared in the library. I think this may be caused by my modification of the file through Sigil. I hope your software can update the file status synchronously, keep only one version of the same file in the library, or prompt the user whether to keep the previous version of the file when opening the library. 
Another request is that your software read the epub file without ignoring the _background-image_ attributes in the _&lt;body&gt;_ tag and the _width_ and _height_ attributes in the *&lt;img&gt;* tag; the full screen image display window should not pop up for _&lt;img&gt;_ attached to *&lt;a&gt;* hyperlinks, whether it's an intra-file link jump or an external link jump.
It would be great to have a transition animation when turning pages, if possible.
Thanks!

**Comment by OptimiliaStudios** [comment]
Books are uniquely identified by the file name, so same book with different file names can be added to the library.

Page transition is available from v1.1.36 onwards, which is being rolled out through Insider Program. To get early access consider joining [Insider Program](https://github.com/OptimiliaStudios/AquileReader/issues/125).
