### ISSUE TITLE
Highliting issue: color does not show!!

### ISSUE THREAD

**Issue by aiskeurim11** [OptimiliaStudios/AquileReader#108]
After I reinstall the apps, color of highliting does not show up. 

<img width="304" alt="Screenshot 2023-02-16 224023" src="https://user-images.githubusercontent.com/125584241/219414687-711a4d3a-648a-4378-8b1a-4dc7f70a57db.png">

And when I start read aloud there's no highlight too!! It's so annoying.

<img width="346" alt="Screenshot 2023-02-16 224239" src="https://user-images.githubusercontent.com/125584241/219415322-052a9d11-1b8f-4d1d-b9b9-978a2812d305.png">

**Comment by samualon** [comment]
Same problem on my laptop. On my desktop highlighting works fine but on my laptop it doesn't.
The 'highlighted' text looks like normal text except it is clickable when I hover over it.
**Laptop:**
CPU: Intel Celeron N4120
GPU: Intel UHD Graphics 600
RAM: 8GB DDR4
SSD of 256GB

**Comment by OptimiliaStudios** [comment]
v1.1.33 onwards has the fix for highlighting related issues.
Please reactivate or open new issue in case you are still facing issues.
