### ISSUE TITLE
3D Page Flip

### ISSUE THREAD

**Issue by rafaelaesdias** [OptimiliaStudios/AquileReader#114]
First of all, I really like the app and I think you did a great job. The only improvement I think this app needs is a 3d page flip option. This would give a better, more book-like experience. I hope you manage to bring this update soon, I would really love it!

**Comment by OptimiliaStudios** [comment]
Page transition is available from v1.1.36 onwards, which is being rolled out through Insider Program. To get early access consider joining [Insider Program](https://github.com/OptimiliaStudios/AquileReader/issues/125).
