### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by Jigglyy** [OptimiliaStudios/AquileReader#116]
It would be nice if there was a setting to enable/disable smooth scrolling, right now I don't think there's any smooth scrolling and it just instantly goes down a few lines

**Comment by OptimiliaStudios** [comment]
Smooth page transition is available from v1.1.36 onwards, which is being rolled out through Insider Program. To get early access consider joining [Insider Program](https://github.com/OptimiliaStudios/AquileReader/issues/125).

**Comment by Foxxsayy** [comment]
@OptimiliaStudios I have smooth scrolling enabled (Windows 11 app). I wanted to ask if there's currently an option for (or if it will be added to include) smooth transitions between chapters? The "jumping" between chapters can be disorienting, especially when reading something with smaller chapters.
