### ISSUE TITLE
FEATURE REQUEST: custom path and/or cloud storage support for library metadata

### ISSUE THREAD

**Issue by d-steffan** [OptimiliaStudios/AquileReader#117]
It would be nice to be able to move the content from `AppData\Local\Packages\21676OptimiliaStudios.AquileReader_k42naep6bwmrc\LocalState\Data` to another custom path which could potentially reside on cloud storage (e.g. OneDrive) but I do not know if its possible to store data outside this folder whilst using UWP-Apps?
I think you should be able to connect to OneDrive out  of UWP Apps, which would be a good alternative too.

Requested functionality partly overlaps with #70.

**Comment by OptimiliaStudios** [comment]
@d-steffan, why do you need to store the app metadata to a different folder/cloud? For backup?

P.S. - Aquile Reader for Android is under development and ready for closed Beta testing, if you are interested in joining the testing program, plz share your Google Play Store email Id.

**Comment by d-steffan** [comment]
@OptimiliaStudios the main reason would be to have the same metadata (collections, bookmarks, notes) on all my devices. Therefore, storing in a custom path residing in a cloud drive would be the easiest solution I would come up with.

P.S. thanks for the invite but unfortunately, I don't have any Android devices.

**Comment by OptimiliaStudios** [comment]
@d-steffan Aquile Reader now supports cross-device sync functionality across Windows and Android devices. This feature is currently available only to Insiders, to get access to the feature early consider joining [Insider program](https://github.com/OptimiliaStudios/AquileReader/issues/125).
