### ISSUE TITLE
Collections by authors

### ISSUE THREAD

**Issue by andersberglund** [OptimiliaStudios/AquileReader#12]
I think it's necessary to sort books by author if you have a lot of books.

**Comment by OptimiliaStudios** [comment]
The feature has been implemented, shall go out in the next update (most likely)

![image](https://user-images.githubusercontent.com/67598009/119249424-14108100-bbb6-11eb-8d0f-d731235c4ab2.png)

**Comment by OptimiliaStudios** [comment]
@andersberglund update is live in the store with this feature, but would be rolling out slowly, to not wait for auto-update and get the update early plz follow the steps - https://aquilereader.wordpress.com/how-to/#app-update

**Comment by andersberglund** [comment]
I have tried the update but only one book of four is listed under the authors label.

![Aquile](https://user-images.githubusercontent.com/2539487/121807686-832d4280-cc55-11eb-897e-8aac2badfc2f.jpg)
