### ISSUE TITLE
CTRL+C not functioning

### ISSUE THREAD

**Issue by Rowvan** [OptimiliaStudios/AquileReader#121]
this is very frustrating. please fix.

**Comment by WhydoIneedusername** [comment]
I'd love this feature as well.
PS: Great app. Thanks

**Comment by OptimiliaStudios** [comment]
Support for ctrl+c will be rolled out in next app update.

FYI - Updates are available sooner in the closed testing group, to join drop an email to optimilia.studios@gmail.com with the email account you use with MS Store.

Try out Aquile Reader on Android with sync between Android and Windows - https://play.google.com/store/apps/details?id=com.optimiliastudios.aquilereader

**Comment by OptimiliaStudios** [comment]
It's available from v1.1.36 onwards, currently being rolled to the insider group. To get early access join [Insider Program](https://github.com/OptimiliaStudios/AquileReader/issues/125).
