### ISSUE TITLE
Can't Change Fonts

### ISSUE THREAD

**Issue by abieganski** [OptimiliaStudios/AquileReader#124]
I'm on latest Windows 11.

When I click the "Text Format" button, nothing happens:
![image](https://github.com/OptimiliaStudios/AquileReader/assets/320048/4799c638-6416-44a6-a10c-539a639b12b5)

**Comment by OptimiliaStudios** [comment]
I am unable to reproduce the issue, can you help with device details and the exact steps you are following which is leading to the issue.

**Comment by abieganski** [comment]
I can't repro now, either. Sorry, I'll close the ticket.
