### ISSUE TITLE
Have an option to disable mouse scrolling through pages

### ISSUE THREAD

**Issue by david-hartman-br** [OptimiliaStudios/AquileReader#127]
Often times while reading and navigating to other reference materials the mouse that I use (which has a touchpad for scrolling) triggers the pages to be turned. This is very inconvenient since I need to figure out which way it scrolled and then navigate back to the page I was on.

**Comment by OptimiliaStudios** [comment]
v1.1.36 onwards has a fix to improve the scrolling through touchpad, but this version is currently under insider testing. To join the insider program you can refer to - https://github.com/OptimiliaStudios/AquileReader/issues/125
