### ISSUE TITLE
Fixed Highlight Button

### ISSUE THREAD

**Issue by githubxinshou** [OptimiliaStudios/AquileReader#128]
Dear developer,

![image](https://github.com/OptimiliaStudios/AquileReader/assets/30167130/6bc90467-4ee0-4f42-a8eb-87e7865a13f1)

When using this on the Windows 10 operating system, my primary concern is the shortcut keys, especially the highlighted shortcut keys. Currently, after selecting content, it is fixed to the translation item. If I want to highlight it, I have to switch again, resulting in a lengthy process. Please understand that not all selections need translation. This not only wastes user bandwidth but also causes inconvenience. What I hope for is something similar to Okular, where I can fix highlighted colors to the sidebar. After selecting a color, it should remain fixed, and when making annotations, it should apply that specific highlight. I am ready to become a member, even though it hasn't fully met my expectations yet. I hope you can make changes. Keep in mind that shorter paths are an advantage. In summary, more customizable shortcut keys would be beneficial, as there seem to be very few currently available.

Best regards.

**Comment by githubxinshou** [comment]
![image](https://github.com/OptimiliaStudios/AquileReader/assets/30167130/f8354e6a-2490-4628-8ad2-acd488140851)
Please update the "Fixed Highlight" button. Thank you.

**Comment by OptimiliaStudios** [comment]
@githubxinshou with v1.1.39 we are rolling out the support for annotation mode - note/highlight and also keyboard shortcuts for highlight and notes. This should address your asks.

But this feature will be rolled out only to insider audience for now, and once stabilized will be rolled out to general public.

In case you want to join the insider program to get the feature early, please share your email id that is used in the Microsoft Store with us at - [optimilia.studios@gmail.com](mailto:optimilia.studios@gmail.com)
