### ISSUE TITLE
Feature Request: Continuous Page scroll (instead of only discreet page switches)

### ISSUE THREAD

**Issue by electrocnic** [OptimiliaStudios/AquileReader#134]
I cannot cope with readers which switch the whole page at once.
I want to be able to read like scrolling through a PDF in Chrome: Seeing the next page and the previous page with a little gap both at the same time. They should scroll smoothly so I can track the context with my eyes instead of being completely lost in space and time of where the text was which I just read. Need this for my focus and context keeping.

**Comment by OptimiliaStudios** [comment]
You can use paginated view. But for continuous vertical scrolling mode, page gap is not planned as of now.
