### ISSUE TITLE
Feature Request: Ability to export highlights for each title individually

### ISSUE THREAD

**Issue by ananggadipa** [OptimiliaStudios/AquileReader#139]
Currently, I can only export highlights for all books simultaneously. I believe it would be beneficial to enable exporting for each book individually.

It would be convenient to have the export option accessible within the current reading book, rather than in the main menu settings as it is now.

Thank you.

**Comment by Tanram** [comment]
I would also very much appreciate this function.

**Comment by OptimiliaStudios** [comment]
@ananggadipa, @Tanram You can achieve this by selecting the desired book in the Collections page and then exporting the collections. Similarly, you can choose to export just highlight/note/bookmark as well.

![image](https://github.com/OptimiliaStudios/AquileReader/assets/67598009/4ce5335d-91a4-48cb-92fb-989520709978)
