### ISSUE TITLE
Simultaneous translation in an extra column

### ISSUE THREAD

**Issue by Tanram** [OptimiliaStudios/AquileReader#142]
It would be great to read a book in a foreign language. On one side in the foreign language and on the other side the book text is automatically translated from the page into the target language.

I have found this function on a Chinese ebook reader so far. It would be great if this function were supported. It is very helpful and useful. It would also be great if you could select the translation site (e.g. deepL).

**Comment by OptimiliaStudios** [comment]
Thanks for suggesting the feature, but this not planned as of now.
