### ISSUE TITLE
Third party SAPI5 voices not detected by Aquile Reader

### ISSUE THREAD

**Issue by marcovth** [OptimiliaStudios/AquileReader#144]
Hello ...

I bought a Cereproc voice https://www.cereproc.com/en/buy-voices

Installed it on a windows computer. Works well with other readers, it's listed there as a new SAPI5 voice.

But it doesn't show up in the list of voices in Aquile Reader. 

Aquile Reader only shows Windows installed system voices and not Third party SAPI5 voices.

Could you look into this?

Thanks a lot.

**Comment by OptimiliaStudios** [comment]
This is limitation from Microsoft on UWP apps, so Aquile Reader can only access Windows installed voices and not third party voices.
