### ISSUE TITLE
Cant access downloaded (via the app) books after app upgrade

### ISSUE THREAD

**Issue by kfir-h** [OptimiliaStudios/AquileReader#145]
steps: 
install win app 1.1.33
download ebooks via the online books section - all downloaded books avalibale
upgrade to 37 version 
when try to open the book get 'Grant Permission' msg - try to grant access (navigate to specify folder)  *.epub file not found   
![2024-01-11_203107](https://github.com/OptimiliaStudios/AquileReader/assets/75068102/72ede077-f070-4774-aa76-1c4e2cd83e9e)

**Comment by OptimiliaStudios** [comment]
This can happen only with the default books that come with the app, "Quick Start Guide" and "The adventure of Sherlock Holmes". Your downloaded or local book files should not face this issue.
Having said that, will look into the problem with the default books.

**Comment by kfir-h** [comment]
It happened also with additional book that I have downloaded from Gutenberg
project.

**Comment by OptimiliaStudios** [comment]
Can you share a screenshot of that? And share the logs to our email id using the "report a bug" option from the app?

**Comment by kfir-h** [comment]
Hi there, I retried it, and it seems to be working, and now it only happens
with the default books.
Anyway, I think it did happen before (?).
pls direct me on how to extract the logs
