### ISSUE TITLE
Keyboard Shortcut for highlighting/annotating

### ISSUE THREAD

**Issue by Tamnac** [OptimiliaStudios/AquileReader#146]
It's common in pdf readers, to be able to hit something like ctrl+h or h after selecting some text to highlight it. It allows a much faster workflow for highlighting. Likewise for notes/bookmarks etc.

Currently highlighting is quite tedious so would be much appreciated.

**Comment by OptimiliaStudios** [comment]
We are working on an adding hot keys for highlight, notes and bookmarks.

Once the feature is ready, it will roll out first to the insider audience and then to everyone (which may take several weeks).
In case you want to join the insider program to get the fix early, please share your email id that is used in the Microsoft Store with us at - [optimilia.studios@gmail.com](mailto:optimilia.studios@gmail.com)

**Comment by OptimiliaStudios** [comment]
@Tamnac The support is being rolled out with v1.1.39 to the insider audience. Request you to join the insider program, try out the new feature and share feedback.

**Comment by S4RTH4K** [comment]
![image](https://github.com/OptimiliaStudios/AquileReader/assets/59368431/a9822601-a80c-4834-b82a-ebec715ec514)
what's the shortcut of highlight as it isn't mentioned anywhere but in case of note it is mentioned i.e N.

**Comment by OptimiliaStudios** [comment]
H+1 / H+2 / ... For different colors.
Click on the highlight button and hover over the colors to see all hot keys.

**Comment by OptimiliaStudios** [comment]
@Tamnac can you plz respond to the mail with your GitHub name, so that we are able to corelate and prioritize your request.
