### ISSUE TITLE
Multiple instances of the AquileReader.

### ISSUE THREAD

**Issue by Megasoft2** [OptimiliaStudios/AquileReader#151]
Hi.

It would be interesting to allow running multiple instances of the application with different e-books simultaneously.
It's possible?

Thx
Megasoft2

**Comment by OptimiliaStudios** [comment]
It's not in the planned backlog as of now.

**Comment by e2heintz** [comment]
Would really like this feature.
Mostly, I read one document at the time, but currently, I am doing research and going through multiple translations of a given text to compare them. Having to find a different program for each file or copying things over somewhere else is kind of annoying really.
