### ISSUE TITLE
Feature Request: Use Spacebar to Flip to Next Page

### ISSUE THREAD

**Issue by jhlim5** [OptimiliaStudios/AquileReader#159]
Feature Request: Use Spacebar to Flip to Next Page

Using the space bar to go to next page would be useful for navigation (like in the Kindle PC app). You could also use Shift-Spacebar to go to previous page.

**Comment by OptimiliaStudios** [comment]
We already support page change using arrow keys, https://aquilereader.wordpress.com/2020/06/14/keyboard-hotkeys/
