### ISSUE TITLE
E-PUB text are not displayed in windows app.

### ISSUE THREAD

**Issue by krutideepa99** [OptimiliaStudios/AquileReader#160]
Hi, while opening my e-pub file only images are displayed but the text are not supported any more. It was working fine 3 months ago.
Some times the epub file is not opening any more.

**Comment by ac-lap** [comment]
Hi,
Can you plz share the book that is not working as expected at optimilia.studios@gmail.com, we will take a look

**Comment by OptimiliaStudios** [comment]
Hi,
Can you plz share the book that is not working as expected at optimilia.studios@gmail.com, we will take a look.

**Comment by krutideepa99** [comment]
Hi, the file is attached below.
[Uploading Stars of Chaos.zip…]()

**Comment by ac-lap** [comment]
Unable to download, plz check the link

**Comment by krutideepa99** [comment]
epub file is not supported here zi[ is not working. Can I share it through mail, if you have any???

**Comment by krutideepa99** [comment]
> Unable to download, plz check the link
Can I share through mail? optimilia.studios@gmail.com

**Comment by OptimiliaStudios** [comment]
yes plz

**Comment by krutideepa99** [comment]
[Stars of Chaos.zip](https://github.com/OptimiliaStudios/AquileReader/files/14626422/Stars.of.Chaos.zip)

**Comment by krutideepa99** [comment]
I have uploaded the file. Please check now.

**Comment by OptimiliaStudios** [comment]
Thanks for sharing the book file, we have identified the issue and fixed. We will roll it out soon starting with insider channel, hence it may take some time to reach everyone.

In case you want to join the insider program to get the fix early, please share your email id that is used in the Microsoft Store with us at - optimilia.studios@gmail.com

**Comment by krutideepa99** [comment]
> Thanks for sharing the book file, we have identified the issue and fixed. We will roll it out soon starting with insider channel, hence it may take some time to reach everyone.
> 
> In case you want to join the insider program to get the fix early, please share your email id that is used in the Microsoft Store with us at - [optimilia.studios@gmail.com](mailto:optimilia.studios@gmail.com)

Thanks a lot. I will update the fixed version  from microsoft store after release of fixed version. Will I get update notification for this fixed version?

**Comment by OptimiliaStudios** [comment]
@krutideepa99 The fix is being rolled out with v1.1.39 to the insider audience.
