### ISSUE TITLE
EPUB not showing text, giving error message

### ISSUE THREAD

**Issue by fidial5** [OptimiliaStudios/AquileReader#161]
![Capture](https://github.com/OptimiliaStudios/AquileReader/assets/162856642/d23bb2a8-e0c1-4238-b2d1-e6e2efe6fa23)
As per title, some of my epubs are not showing any text. I've tried opening on other epub readers, on both PC and Android, and they work fine, so I believe this is an issue with the app. Is there any way to fix this?

**Comment by ac-lap** [comment]
Hi,
Can you plz share the book that is not working as expected at optimilia.studios@gmail.com, we will take a look

**Comment by OptimiliaStudios** [comment]
Hi,
Can you plz share the book that is not working as expected at optimilia.studios@gmail.com, we will take a look.

**Comment by fidial5** [comment]
The chapters are all blank.

 Thousand Autumns Vol 3.epub
<https://drive.google.com/file/d/15oD9gts3FD1j8uZNgx22oZYVzPfo9xlH/view?usp=drive_web>

 Stars of Chaos Vol 2.epub
<https://drive.google.com/file/d/15rEuPEbTBF9eEnRXXUqxJVjRz86et97T/view?usp=drive_web>

**Comment by OptimiliaStudios** [comment]
@fidial5 I am unable to access the files, plz provide access to optimilia.studios@gmail.com
