### ISSUE TITLE
Cloud Sync connection

### ISSUE THREAD

**Issue by vi-datageek** [OptimiliaStudios/AquileReader#178]
I am trying to activate cloud sync on the desktop app. I can enter my Google credentials but it doesn't establish the connection. It tries to connect for some time and then states that it could connect to the Google drive.
![Screenshot 2024-05-25 105021](https://github.com/OptimiliaStudios/AquileReader/assets/170780736/136f6697-5e96-414e-8f6c-0960f1167cce)

**Comment by mchurch13** [comment]
I had the same issue.  For me, it seems to be connected with 2Factor Authentication from Google.  I had to go into the Security settings for my Google account and turn off 2FA temporarily. Once I did, I could authorize the connection, then turn 2FA back on. PC had issues with this, but the Android app on my phone did not.

**Comment by vi-datageek** [comment]
That works! Thanks @mchurch13
