### ISSUE TITLE
App closes when trying to open a book

### ISSUE THREAD

**Issue by Kanishka2112** [OptimiliaStudios/AquileReader#191]
The app closes as soon as I try to open a book and start reading.

**Comment by daqoblade** [comment]
I am having the same problem after the new update on a Samsung S22 Ultra. All my PC devices are working fine.

**Comment by OptimiliaStudios** [comment]
@Kanishka2112 , @daqoblade - In the latest update we had updated the version of bunch of dependent packages which could have caused this issue. We have reverted the changes and rolled out the last stable build as v 1.1.29.
We are really sorry for the inconvenience.

**Comment by Kanishka2112** [comment]
I updated the app but it's the same. The moment it is synced, the app closes. The moment I open a book, it closes

**Comment by daqoblade** [comment]
I uninstalled and reinstalled the app and now it's crashing upon opening for me.

**Comment by Noguito** [comment]
I have the same problem. Out of nowhere, when I tried to open the app, it would load for a few seconds and then close. I then tried uninstalling and reinstalling it, and now it opens for half a second (it shows the app icon) but nothing more. I have generated an error report which I am attaching. Thank you for your excellent work.

`Build fingerprint: 'POCO/alioth_global/alioth:13/TKQ1.221114.001/V816.0.3.0.TKHMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2024-08-02 21:47:22.766239887-0500
Process uptime: 1s
ZygotePid: 923
Cmdline: com.optimiliastudios.aquilereader
pid: 30331, tid: 30331, name: os.aquilereader >>> com.optimiliastudios.aquilereader <<<
uid: 10492
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr
  x0 0000000000000000 x1 000000000000767b x2 0000000000000006 x3 0000007f9cbd760
  x4 3032322f321f1f30 x5 3032322f321f1f30 x6 3032322f321f1f30 x7 7f7f7f7f7f7f7f7f
  x8 00000000000000f0 x9 0000007d49c76d30 x10 0000000000000001 x11 0000007d49ceb9c8
  x12 0000007f9cbb884 x13 0000000000000005 x14 0000000000000000 x15 0000007d49c7aa02
  x16 0000007d49d56a80 x17 0000007d49d2f650 x18 0000007d69e16000 x19 000000000000767b
  x20 000000000000767b x21 00000000ffffffff x22 b400007bff3d6000 x23 0000007c2906eea7
  x24 b400007c98ba0800 x25 0000007c2906eea7 x26 0000007c31061180 x27 0000000000000000
  x28 0000007f9cbe540 x29 0000007f9cbd7e0
  lr 0000007d49edc948 sp 0000007f9cbd740 pc 0000007d49cdc974 pst 0000000000001000
backtrace:
  #00 pc 0000000000084974 /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 8a2277585401a6103d671ealf801ed52)
  #01 pc 000000000001f360 /data/app/~~tDAsqYFI7sTqVcghFFZ_Vw==/com.optimiliastudios.aquilereader-srLfC_iwgrt/M36bjPQ4Jw==/split_config.arm64_v8a.apk!libmono-android.release.so (xamarin::android::Helpers::abort_application()+8) (BuildId: 7feeaaea39e016c6c3bff7e94f0388b7b31f6ba)
  #02 pc 0000000000035660 /data/app/~~tDAsqYFI7sTqVcghFFZ_Vw==/com.optimiliastudios.aquilereader-srLfC_iwgrt/M36bjPQ4Jw==/split_config.arm64_v8a.apk!libmono-android.release.so (xamarin::android::internal::MonodroidRuntime::mono_log_handler(char const*, char const*, char const*, int, void*)+144) (BuildId: 7feeaaea39e016c6c3bff7e94f0388b7b31f6ba)
  #03 pc 00000000001d7464 /data/app/~~tDAsqYFI7sTqVcghFFZ_Vw==/com.optimiliastudios.aquilereader-srLfC_iwgrt/M36bjPQ4Jw==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (BuildId: 48e3f0902f459e3d303103a665474210c2406617)
  #04 pc 00000000001d7590 /data/app/~~tDAsqYFI7sTqVcghFFZ_Vw==/com.optimiliastudios.aquilereader-srLfC_iwgrt/M36bjPQ4Jw==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (BuildId: 48e3f0902f459e3d303103a665474210c2406617)
  #05 pc 0000000000140e48 /data/app/~~tDAsqYFI7sTqVcghFFZ_Vw==/com.optimiliastudios.aquilereader-srLfC_iwgrt/M36bjPQ4Jw==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (BuildId: 48e3f0902f459e3d303103a665474210c2406617)
  #06 pc 000000000013fla4 /data/app/~~tDAsqYFI7sTqVcghFFZ_Vw==/com.optimiliastudios.aquilereader-srLfC_iwgrt/M36bjPQ4Jw==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (BuildId: 48e3f0902f459e3d303103a665474210c2406617)
  #07 pc 00000000001527a0 /data/app/~~tDAsqYFI7sTqVcghFFZ_Vw==/com.optimiliastudios.aquilereader-srLfC_iwgrt/M36bjPQ4Jw==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (BuildId: 48e3f0902f459e3d303103a665474210c2406617)
  #08 pc 0000000000004f00 <anonymous:7d58f01000>
  #09 pc 000000000008d974 /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 8a2277585401a6103d671ealf801ed52)
  #10 pc 000000000001f360 /data/app/~~tDAsqYFI7sTqVcghFFZ_Vw==/com.optimiliastudios.aquilereader-srLfC_iwgrt/M36bjPQ4Jw==/split_config.arm64_v8a.apk!libmono-android.release.so (xamarin::android::Helpers::abort_application()+8) (BuildId: 7feeaaea39e016c6c3bff7e94f0388b7b31f6ba)
  #11 pc 0000000000035660 /data/app/~~tDAsqYFI7sTqVcghFFZ_Vw==/com.optimiliastudios.aquilereader-srLfC_iwgrt/M36bjPQ4Jw==/split_config.arm64_v8a.apk!libmono-android.release.so (xamarin::android::internal::MonodroidRuntime::mono_log_handler(char const*, char const*, char const*, int, void*)+144) (BuildId: 7feeaaea39e016c6c3bff7e94f0388b7b31f6ba)
  #12 pc 00000000001d7464 /data/app/~~tDAsqYFI7sTqVcghFFZ_Vw==/com.optimiliastudios.aquilereader-srLfC_iwgrt/M36bjPQ4Jw==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (BuildId: 48e3f0902f459e3d303103a665474210c2406617)
  #13 pc 00000000001d7590 /data/app/~~tDAsqYFI7sTqVcghFFZ_Vw==/com.optimiliastudios.aquilereader-srLfC_iwgrt/M36bjPQ4Jw==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (BuildId: 48e3f0902f459e3d303103a665474210c2406617)
  #14 pc 0000000000140e48 /data/app/~~tDAsqYFI7sTqVcghFFZ_Vw==/com.optimiliastudios.aquilereader-srLfC_iwgrt/M36bjPQ4Jw==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (BuildId: 48e3f0902f459e3d303103a665474210c2406617)
  #15 pc 000000000013fla4 /data/app/~~tDAsqYFI7sTqVcghFFZ_Vw==/com.optimiliastudios.aquilereader-srLfC_iwgrt/M36bjPQ4Jw==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (BuildId: 48e3f0902f459e3d303103a665474210c2406617)
  #16 pc 00000000001527a0 /data/app/~~tDAsqYFI7sTqVcghFFZ_Vw==/com.optimiliastudios.aquilereader-srLfC_iwgrt/M36bjPQ4Jw==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (BuildId: 48e3f0902f459e3d303103a665474210c2406617)
  #17 pc 0000000000004f00 <anonymous:7d58f01000>`

**Comment by OptimiliaStudios** [comment]
@Kanishka2112 , @daqoblade , @Noguito - plz install the latest update, v1.1.30, the changes have been reverted, and it should now be working.

**Comment by Noguito** [comment]
Thank you! Everything seems to be working properly! Greetings

**Comment by daqoblade** [comment]
It seems to be working for me too. Thanks!
