### ISSUE TITLE
Search default parameter (whole book)

### ISSUE THREAD

**Issue by flobo09** [OptimiliaStudios/AquileReader#20]
Hey team, thanks for the great work, this has become my main ebook reading on windows since Edge stopped doing it. 

There is one thing though that keeps annoying me. 
99.9 % of the time, when i search something in a book, i want to search in the whole book.
Unless i'm mistaken, it keeps defaulting back to current chapter which i find a bit annoying. 

Could you please persist the choice so that it stays what was last selected ? 

Thank you !

**Comment by ac-lap** [comment]
Noted.

**Comment by OptimiliaStudios** [comment]
Noted.

**Comment by OptimiliaStudios** [comment]
@flobo09 update is live in the store with this feature, but would be rolling out slowly, to not wait for auto-update and get the update early plz follow the steps - https://aquilereader.wordpress.com/how-to/#app-update
