### ISSUE TITLE
Dark Reading mode

### ISSUE THREAD

**Issue by mapedersen** [OptimiliaStudios/AquileReader#218]
Hello. There is a dark mode for the app itself but not when reading. Opening up a book late at night is simply not possible as of now.

**Comment by srabonuwu** [comment]
> How is this not possible?!? This reader was recommended as the best ePub reader, but I am staring at the sun when I try to read something with this reader. How and why is there no dark mode in this day and age?!?
> 
> Edit: I stand corrected. Turns out, there IS a dark mode. I discovered this after I uninstalled it. So, I reinstalled it.

Can you tell me how you can find this? I can only find the dark mode for the app not for the reader
