### ISSUE TITLE
Can't open ebooks while offline

### ISSUE THREAD

**Issue by LudovicBouvierJohnston** [OptimiliaStudios/AquileReader#22]
I have been stuck where I couldn't read my favourite books while travelling . I have noticed that I need to enable the tethering feature on my phone just so I can get past the opening book loading screen. Is this is a bug? I am not sure if the app is able to be used in offline mode. Thanks for your help! 😀

**Comment by ac-lap** [comment]
We have added the support for offline reading, will go out in the next release.

**Comment by OptimiliaStudios** [comment]
We have added the support for offline reading, will go out in the next release.

**Comment by OptimiliaStudios** [comment]
@LudovicBouvierJohnston update is live in the store but would be rolling out slowly, to not wait for auto-update and get the update early plz follow the steps - https://aquilereader.wordpress.com/how-to/#app-update

**Comment by LudovicBouvierJohnston** [comment]
Working great thank you!
