### ISSUE TITLE
RE: BUG!!!!!!! 

### ISSUE THREAD

**Issue by DIVASUBBY** [OptimiliaStudios/AquileReader#28]
I sent the files that were not opening to you by mail and then no reply is there anything you can do to fix it or not

**Comment by OptimiliaStudios** [comment]
Apologies for not replying back in time, but can you confirm if you sent the files named "* Legendary Master is Wife *", "* Useless Rebirth *", etc? If yes, then we have fixed the issue and update should start rolling out some time next week.

**Comment by DIVASUBBY** [comment]
yes, those were from me thank you i am looking forward to the update

**Comment by OptimiliaStudios** [comment]
@DIVASUBBY, update is live in the store but would be rolling out slowly, to not wait for auto-update and get the update early plz follow the steps - https://aquilereader.wordpress.com/how-to/#app-update
