### ISSUE TITLE
More Extension Support 

### ISSUE THREAD

**Issue by dim26** [OptimiliaStudios/AquileReader#3]
Please add support for more extensions to make the app an all-round reader. Support for cbr, cbz, pdf etc would be great. Also is it possible to add live tile feature?

**Comment by OptimiliaStudios** [comment]
Hello,
More file format support is in our planned road-map, though it's not very immediate.
For live tiles, can you share some thoughts on what info you would like to see there?

**Comment by dim26** [comment]
> For live tiles, can you share some thoughts on what info you would like to see there?

Pinning individual books would be great. The tile can show the book cover and when it flips or whatever animation you decide happens, it could tell how much progress we have done.

**Comment by OptimiliaStudios** [comment]
Live tiles are no longer supported on Windows.
