### ISSUE TITLE
The library view does not remember selected sub-view and sorting options

### ISSUE THREAD

**Issue by rubin55** [OptimiliaStudios/AquileReader#30]
The library view does not remember which sub-view (i.e., `All Books`, `Favorites`, `Downloads`, `Reading`, `Not Started`, `Completed`) you selected after switching to another view and/or restarting the app.

Additionally, it also does not remember which sorting option you selected (i.e., `Title`, `Author`, `Import Time`, `Last Read Time`). This is somewhat of a hassle with large book collections (i.e., you open the app, go to your library and want to select one of the recently read books, beyond what the main home screen offers you, now you first have to select the `Reading` sub-view, to eliminate finished books, and then click on the sort option `Last Read Time`, every time you open the app or switch from a different view).

Great app, think it has the potential to be the best reader out there, bought the lifetime premium option yesterday to support :-)

**Comment by OptimiliaStudios** [comment]
Fair point. We are making few more changes in the library view, we shall include these as well.

**Comment by OptimiliaStudios** [comment]
@rubin55 update is live in the store with this feature, but would be rolling out slowly, to not wait for auto-update and get the update early plz follow the steps - https://aquilereader.wordpress.com/how-to/#app-update
