### ISSUE TITLE
Exception when opening: "Clojure for the Brave and True"

### ISSUE THREAD

**Issue by rubin55** [OptimiliaStudios/AquileReader#33]
When attempting to open the epub "Clojure for the Brave and True", The application returns an error message: "Something went wrong! Sorry it looks like something just went wrong. Try opening the file again. If the problem persists, please contact support."

Trying to re-open the file does not change the error message, this epub won't open.

I've sent you the file via [WeTransfer](https://wetransfer.com/) on your email address: optimilia.studios@gmail.com. Note that the transfer is only valid for 7 days.

**Comment by OptimiliaStudios** [comment]
App update with fix for handling this book has been released, v1.0.39
