### ISSUE TITLE
Blank page when opening: "Structure and Interpretation of Computer Programs, 2nd Edition"

### ISSUE THREAD

**Issue by rubin55** [OptimiliaStudios/AquileReader#36]
When attempting to open "Structure and Interpretation of Computer Programs, 2nd Edition", Aquile shows a blank page. The table of contents does show, but selecting any entry does not return a page. It does change the percentage completed.

I've sent you the file via [WeTransfer](https://wetransfer.com/) on your email address: optimilia.studios@gmail.com. Note that the transfer is only valid for 7 days.

**Comment by OptimiliaStudios** [comment]
Duplicate of #31
