### ISSUE TITLE
I'm here again, some files are still not working. although the ones i sent to you are working now but i found others that aren't opening

### ISSUE THREAD

**Issue by DIVASUBBY** [OptimiliaStudios/AquileReader#37]
I'm Here AGAIN. some files are not opening, although the ones i sent to you are working now, but i found new files that aren't opening again

**Comment by ac-lap** [comment]
Plz share the files with us over e-mail, we will take a look

**Comment by OptimiliaStudios** [comment]
Plz share the files with us over e-mail, we will take a look
