### ISSUE TITLE
Feature Request : Translation

### ISSUE THREAD

**Issue by puschie286** [OptimiliaStudios/AquileReader#38]
Hi,
would be nice to have a translate feature right in the text context menu.

Personally i prefer DeepL ( [API](https://www.deepl.com/docs-api) ) but anything like google translate ( [API](https://www.labnol.org/code/19909-google-translate-api) ) would be awesome. 

the holy grail would be a full translation of the ebook. modern translators have much better results with longer text and can even track a personal dictionary for personal preferences.
but guess that's not possible ( in free tier - so this require linking your account )

**Comment by OptimiliaStudios** [comment]
This is something which we are tracking as a backlog item, can't commit on the date, but we are looking into it.

**Comment by OptimiliaStudios** [comment]
@puschie286 update is live in the store with this feature, but would be rolling out slowly, to not wait for auto-update and get the update early plz follow the steps - https://aquilereader.wordpress.com/how-to/#app-update
