### ISSUE TITLE
Folder appears blank when pinned books are put inside a folder in Start Menu

### ISSUE THREAD

**Issue by ashishkupadhyay** [OptimiliaStudios/AquileReader#40]
First of all thanks for adding this feature, but there is a bug. When you add Live Tiles of books inside a folder, the folder becomes blank. This happens because live tiles get turned off when they are in a folder (which is the case for all apps and not only Aquile). The problem with Aquile is that Book Cover art disappears when you turn off live tiles of pinned books, so when they are put inside a folder, the folder appears blank which does not happens with apps like Groove Music.
![image](https://user-images.githubusercontent.com/84338228/118522943-422b3680-b75a-11eb-9853-6920ca6df40b.png)
![image](https://user-images.githubusercontent.com/84338228/118523417-be257e80-b75a-11eb-90c9-49eda5431689.png)
![image](https://user-images.githubusercontent.com/84338228/118523973-4dcb2d00-b75b-11eb-881d-df300c9ac7f6.png)
![image](https://user-images.githubusercontent.com/84338228/118524186-82d77f80-b75b-11eb-906c-8f4147163963.png)
![image](https://user-images.githubusercontent.com/84338228/118524733-17da7880-b75c-11eb-94bc-91d662333f18.png)
![image](https://user-images.githubusercontent.com/84338228/118524872-3d678200-b75c-11eb-981a-ef5237fbf871.png)

**Comment by OptimiliaStudios** [comment]
Thanks for reporting the issue, but somehow I am not able to repro it.
Tiles folder
![image](https://user-images.githubusercontent.com/67598009/119249090-a8c5af80-bbb3-11eb-9c2b-154818a69cdb.png)

Tiles folder expanded
![image](https://user-images.githubusercontent.com/67598009/119249096-b2e7ae00-bbb3-11eb-894b-559e20bbb858.png)

So, live tiles are not turned-off when the tiles are in the folder.
But I understand when the live tile is turned off, the tile needs to be more descriptive. The reason the normal tile does not have cover image is, coz it distorts the aspect ratio and the tile looks ugly, but the live tile maintains the aspect ratio.
I'll see what's best can be done here.

Tiles with live tile turned off
![image](https://user-images.githubusercontent.com/67598009/119249160-0ce87380-bbb4-11eb-9d82-dd703c2507df.png)

**Comment by Trsier** [comment]
Thanks for taking out time to work on this. I meant that live tiles appears to be turned off when they are in a folder (when folders are not expanded). I don't know a thing about UWP app development 😅 and I noticed that the behaviour of Book tiles is same when they are inside a folder and when their "live tiles" are turned off manually. I mean, in both cases they are blank. Again, thanks for working on this and I hope you will find a solution for this and make it work just like Groove music.
