### ISSUE TITLE
 loss of control when opening epub from 'open with' feature

### ISSUE THREAD

**Issue by jack-mohn** [OptimiliaStudios/AquileReader#43]
If I open an epub through the library function the two top lines are present on functioning ( epub name and control line) function perfectly.

If I attempt to open an epub by clicking on the epub (Aquile is the open open with default) the two control lines overlap each other. Only the file name line functions. I cannot change fonts over line spacing or only thing else from that control line. Until this was occurred Aquile was my default reader, replacing the Calibre internal reader.

I hope you can repair this fault. If not I will have to keep looking.
                                                      Thanks, Jack

**Comment by OptimiliaStudios** [comment]
Can you plz provide screenshot of the app when controls are not accessible, that will help me understand the precise issue.
From what I have understood -
1. If you open from within the app, then the reader works fine.
2. But if you open book from the file system with Aquile Reader, then there is some issue of which you will share the screenshot.

When did this issue start happening? After app update? What is the current version of the app?

**Comment by jack-mohn** [comment]
I think it had something to do with too many things in the catalogue.  I uninstalled/reinstalled and everything is fine.  Purchased the pro update so everything seems to fine.
  Sorry to have bothered you.    Jack
