### ISSUE TITLE
Feature Request: Ability to export/share/print/send to onenote :highlights & Notes

### ISSUE THREAD

**Issue by jakkaas** [OptimiliaStudios/AquileReader#44]
Ability to export/share/print/send to onenote :highlights & Notes

**Comment by OptimiliaStudios** [comment]
This feature is under development, and will go out with the next app release. Will update this thread again once the update is released.

**Comment by OptimiliaStudios** [comment]
@jakkaas update is live in the store with this feature, but would be rolling out slowly, to not wait for auto-update and get the update early plz follow the steps - https://aquilereader.wordpress.com/how-to/#app-update
