### ISSUE TITLE
Infinite Loading On Opening Any Book

### ISSUE THREAD

**Issue by Bushuo** [OptimiliaStudios/AquileReader#46]
Hi, I got the same faulty behaviour as described in #24 
Here are the logs.
The _log3.log happened as I immediately closed the application after opening a book.
_log4.log got created when I let it load a second and the App gets unresponsive, apart from keeping spinning.

[Logs.zip](https://github.com/OptimiliaStudios/AquileReader/files/6639996/Logs.zip)

If it helps, I have
Windows 10 Pro
Version	20H2
OS build	19042.1052
Experience	Windows Feature Experience Pack 120.2212.2020.0
with an Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz   3.30 GHz Processor and 16 GB of RAM

**Comment by OptimiliaStudios** [comment]
This from the past experience appears to be crash in the edgehtml.dll. Will you be open to installing a private build of the app (with more logging and maybe potential fix) on your machine to help us debug this. If yes, plz drop a mail at optimilia.studios@gmail.com , don't want to share private build publicly.

**Comment by Bushuo** [comment]
Yes sure :) I dropped you an email

**Comment by OptimiliaStudios** [comment]
Closing as the issue has been fixed.
