### ISSUE TITLE
FEATURE REQUEST: option to switch read pages percentage to n. read pages / total pages

### ISSUE THREAD

**Issue by eirinn1975** [OptimiliaStudios/AquileReader#47]
Hello,
I think it would be a nice addition to be able to switch the read progress percentage to read pages against book pages

**Comment by OptimiliaStudios** [comment]
Right now I render only one chapter at a time, and the page count changes based on the size of the app window. To know the total page count of the book means either I'll have to load all the chapters (which will make the book load slow) or I'll have to come up with some guess estimate page count which might change when the chapter actually loads, and I don't think it will be a good experience seeing total page count change.
Let me know what you think.

I'll see if there is some other way to do it which is more deterministic, but cannot commit on this feature.

**Comment by eirinn1975** [comment]
I see what you mean and understand. The pages number would probably also change if you change the window size. That can get pretty complicated.


--
Maximiliano Morsia
Hakamäentie 31, 26840 Rauma - Finland
tel. +358 (0) 40 175 1973


________________________________
