### ISSUE TITLE
FEATURE REQUEST: Add Pdf Support

### ISSUE THREAD

**Issue by narottammurmu** [OptimiliaStudios/AquileReader#49]
Hello,

Can you guys add support for pdf, please?

**Comment by Jude24to25** [comment]
And the ability to highlight those pdfs, too! 🤓👍

**Comment by OptimiliaStudios** [comment]
Support for pdf is planned but is a backlog item, as there are not good pdf parsing libraries available for UWP apps. I am looking into what best support can be provided for PDFs within the app.

**Comment by narottammurmu** [comment]
Thank you for replying. I used to use the built-in pdf reader in Windows 8. If you could make it like that it would be helpful.

**Comment by OptimiliaStudios** [comment]
We have added PDF support from v1.1.53 of Windows and v1.1.54 of Android
