### ISSUE TITLE
Highlighting: Incomplete highlights

### ISSUE THREAD

**Issue by Jude24to25** [OptimiliaStudios/AquileReader#50]
Here's what happens:
1. Highlight text.
2. Delete that highlight.
3. Re-highlight the same text
4. RESULT: Only bits and pieces of the text are highlighted. I have to re-highlight the same text a few times for the complete text to show as highlighted.

**Comment by OptimiliaStudios** [comment]
This is the limitation of the library we use for highlighting, I'll try to fix it in some round about way if possible.

One **workaround** for this is, when you delete the highlight, and you need to re-highlight the same text, close the book and open it again, then the highlight of the same text would work as expected. 
I know it's not ideal solution, but I hope this is not a frequent issue, as this happens only when the exact same text is highlighted again, if subset or overlapping set is highlighted then the issue does not happen.

**Comment by OptimiliaStudios** [comment]
Highlighting related improvements are available from v1.1.33 onwards, plz try it out. In case you still are facing issues plz reactivate or create new issue.
