### ISSUE TITLE
Reader Problems

### ISSUE THREAD

**Issue by bitchyass** [OptimiliaStudios/AquileReader#53]
There are ads in the reader, please remove them

**Comment by OptimiliaStudios** [comment]
Hi,
We are working on providing more customization options around Ads, and one of the options would allow to remove Ad from the reader.

**Comment by OptimiliaStudios** [comment]
We have released option to select Ad preference, hence closing this issue

**Comment by bitchyass** [comment]
That's pretty cool, thanks for the update and the great job on the app!
