### ISSUE TITLE
unable to lookup even for some simple words

### ISSUE THREAD

**Issue by hungrysnake** [OptimiliaStudios/AquileReader#57]
is it possible to change to other online dictionary? like cambridge dict

![image](https://user-images.githubusercontent.com/42885440/126103401-57c9cf58-932b-48c9-8b46-fd94cde29464.png)

the dictionary is working as some words can be found.

![image](https://user-images.githubusercontent.com/42885440/126103495-f05a314e-f8f5-4f82-bbdc-121eb09a306f.png)

**Comment by OptimiliaStudios** [comment]
@hungrysnake with the last release of Aquile Reader, dictionary language support was added, with that this issue would go away.
Hence closing the issue.
