### ISSUE TITLE
Ctrl-mousewheel scrolling zooms and advances page

### ISSUE THREAD

**Issue by johnwang16** [OptimiliaStudios/AquileReader#6]
When reading a book, holding down ctrl and using the mousewheel changes the text size as expected, however the event also gets captured as a page turn. Ctrl-scroll should only change text size.

**Comment by OptimiliaStudios** [comment]
Hi,
ctrl+scroll zooms the entire screen which is something we don't want users to do. You can use the font size slider to increase the font size or is there any other specific reason you had to use ctrl+scroll (if so we can try to address that)?

**Comment by johnwang16** [comment]
It's mainly force of habit as ctrl-scroll changes text size in most applications, and I would imagine other users may also wind up doing the same thing.
