### ISSUE TITLE
Feature Request: Mobile Support

### ISSUE THREAD

**Issue by jdlax** [OptimiliaStudios/AquileReader#60]
The app is really amazing. However, I would like to request if there would mobile support for this. I love reading between my phone and laptop, and I think it would be perfect if they could be synced with each other so I could read anywhere outside without having to bring my laptop the whole time.

I will also avail a premium subscription if this is to be granted.

**Comment by OptimiliaStudios** [comment]
This is a very valid ask, we are planning to start work on a Android app with sync support, but it will take some time and hence cannot comment on any timelines yet.

**Comment by OptimiliaStudios** [comment]
Thanks for your feedback, we are actually working on an Android version of the app, it's currently in closed testing, if you are interested in trying out, plz share your Google Play Store login email Id, and will add you to the testing group.
You can reach out to us at [optimilia.studios@gmail.com](mailto:optimilia.studios@gmail.com)

https://play.google.com/store/apps/details?id=com.optimiliastudios.aquilereader
