### ISSUE TITLE
Feature Request - Display total % of pages read

### ISSUE THREAD

**Issue by RajkumarGSG** [OptimiliaStudios/AquileReader#61]
As of now, unable to know how many pages we have read among the total pages. If there is some sort of info like
- % of pages read 
- No of pages read
it will be great experience, and will get idea how much progressed in reading and how much remaining.

Also would be nice to display currently reading chapter name on top or bottom.

As a reference, I have attached screenshots from Google Books.
![Screenshot_20210914-173754_Google Play Books](https://user-images.githubusercontent.com/19187864/133256531-bacd1e76-9720-4413-9b66-527fdc954ff8.jpg)
![Screenshot_20210914-173805_Google Play Books](https://user-images.githubusercontent.com/19187864/133256547-c5b461d1-e9d0-476e-a0eb-c5440d945789.jpg)

**Comment by OptimiliaStudios** [comment]
All the things you have requested are already present at the bottom of the reader.

![image](https://user-images.githubusercontent.com/67598009/135385123-2b4cb9dd-fcfb-4f22-9cbf-392c5da6c0df.png)

1 - current chapter name
2 - num of pages read in the current chapter
3 - % of book read.
