### ISSUE TITLE
Definitions not working

### ISSUE THREAD

**Issue by redqua** [OptimiliaStudios/AquileReader#63]
When I highlight a word, either by dragging or double clicking, the menu that pops up says "Definition not found" and a link that says "Look this up on the web" (which does work but it opens in my browser the search for the word).

**Comment by OptimiliaStudios** [comment]
Hi
Currently the definition is only limited to English language, we are looking into adding more language support, but cannot commit any date yet.

**Comment by OptimiliaStudios** [comment]
Definition now supports multiple different languages.
