### ISSUE TITLE
one of files is not opening i dont know why as other ones work just fine isit a problem with the file?

### ISSUE THREAD

**Issue by Dasharath20206** [OptimiliaStudios/AquileReader#64]
its a epub file of 'World Domination System' other epubs open but not this one the epub opens in other readers too but not in this

**Comment by ac-lap** [comment]
Hi,
Can you plz share the epub file which is not working with us?
Also, share the logs - https://aquilereader.wordpress.com/how-to/#collect-logs

Share both the epub file and log files at optimilia.studios@gmail.com

**Comment by Dasharath20206** [comment]
Thank you Anubhav
I have sent the log and the file that does not seem to be working to the
gmail u have given in your mail. I hope you can help me with this and get
it working again

**Comment by OptimiliaStudios** [comment]
As communicated over e-mail, the issue has been fixed and the update has already been released.
