### ISSUE TITLE
Feature Request: add Page-turning animation

### ISSUE THREAD

**Issue by TranBaoAn-MD** [OptimiliaStudios/AquileReader#65]
Page-turning animation is cool!

**Comment by OptimiliaStudios** [comment]
Hi,
We are looking into adding some kind of page turn animation, but cannot commit to any date yet.

**Comment by OptimiliaStudios** [comment]
Page transition is available from v1.1.36 onwards, which is being rolled out through Insider Program. To get early access consider joining [Insider Program](https://github.com/OptimiliaStudios/AquileReader/issues/125).
