### ISSUE TITLE
[Feature Request] Add option like "hide/display title bar" in settings

### ISSUE THREAD

**Issue by thekips** [OptimiliaStudios/AquileReader#69]
The interface of reading consist of pages of the book, tool bar and title bar, which is very waste of place. I think we can be more immersed in the book when reading after hiding these unimportant interface.

**Comment by OptimiliaStudios** [comment]
You can enter the full screen mode to remove title and tool bars and Windows task bar for true immersive reading.

![image](https://user-images.githubusercontent.com/67598009/146643326-193ef64f-4ad8-4e6e-a853-6010090741be.png)

**Comment by thekips** [comment]
![image-20220419172053546](https://cdn.jsdelivr.net/gh/thekips/PicGo/Notes/2022/04/20220419172053.png)

Using fullscreen mode may not be a good idea cause the ratio of books is not right then, and I think we can hide the toolbar by clicking the center area. After that, we will not see the big double bar anymore. The final effect may be like the following picture, which is a screenshot I take from foliate. 

![screenshot](https://johnfactotum.github.io/foliate/screenshot.png)
