### ISSUE TITLE
Display title (and perhaps author) in cover view

### ISSUE THREAD

**Issue by vor0nwe** [OptimiliaStudios/AquileReader#7]
Some e-books either do not have a cover, or have a cover that doesn’t show the book’s title or author. This happens most notably with free e-books, like those from Gutenberg.org:

![afbeelding](https://user-images.githubusercontent.com/76925/104326695-4d3f3300-54ea-11eb-843f-314298a356e2.png)

Would it be possible to display at least the title, and perhaps the author, just below the cover? That way, it would always be clear what the three first books in the second row of my library are (shown above), without having to open them...

**Comment by OptimiliaStudios** [comment]
Fair ask, will see what I can do here.

**Comment by Melponeo** [comment]
Same issue here. Maybe it helps to let you know, that all these ebooks are .epub file type and drm free.
![aquile_reader_no_titles](https://user-images.githubusercontent.com/78921954/107664038-4f80e280-6c8c-11eb-9c41-e32bd536913f.PNG)
Otherwise i realy do like aquile reader.

**Comment by OptimiliaStudios** [comment]
@vor0nwe  Support for displaying title under the book in library view was added in 1.0.32 version of the app. Hope you already tried it out, and apologies for notifying you late.

**Comment by OptimiliaStudios** [comment]
@Melponeo  , in the current update 1.0.37 we have added support for different types of epub files, can you plz try again and see if you are able to open the books now? If you are still facing issue, can you plz send few books to us for debugging at optimilia.studios@gmail.com?

1.0.37 update is live in the store but would be rolling out slowly, to not wait for auto-update and get the update early plz follow the steps - https://aquilereader.wordpress.com/how-to/#app-update

**Comment by vor0nwe** [comment]
> @vor0nwe Support for displaying title under the book in library view was added in 1.0.32 version of the app. 

I did notice it; both the title under each book, and also the title inside the cover when there's no cover available. Thank you very much!

**Comment by OptimiliaStudios** [comment]
Closing the bug as the requested items have been completed.
