### ISSUE TITLE
Takes a lot of RAM.

### ISSUE THREAD

**Issue by vatsdimri** [OptimiliaStudios/AquileReader#72]
Even for smaller books of about 2mb it takes around 200mb RAM. And as the size of the book increases the resources (mainly RAM and CPU) it uses go crazy for example for this 17 mb epub book that I had It was taking more than 2gb RAM and sometime 3 or even 4gb. 
![Screenshot 2022-01-05 164225](https://user-images.githubusercontent.com/61177515/148209130-b004188a-8013-4e55-ad9d-287c0418d895.png)

![Screenshot 2022-01-05 164317](https://user-images.githubusercontent.com/61177515/148209155-33288289-3abb-471b-b06d-1f1c1d4b052e.png)

**Comment by OptimiliaStudios** [comment]
In our current update, we have improved the memory management of the app. For some of our test books, RAM consumption is down by upto 70%.
The update would be live in the store in few days

**Comment by vatsdimri** [comment]
Great. Thanks. I really like the layout of the app it was just taking too much. I'll check out the new version.

**Comment by OptimiliaStudios** [comment]
App update with the fix has been released, but the update roll-out will happen slowly and might take some time to reach you. 
You can forcefully fetch for the update by following the steps here - https://aquilereader.wordpress.com/how-to/#app-update
