### ISSUE TITLE
Highlighting: color does not show

### ISSUE THREAD

**Issue by philaurb** [OptimiliaStudios/AquileReader#74]
1. I´m highlighting a text
2. the highlighted area is marked as highlighted but has no color, as if not highlighted at all.

![image](https://user-images.githubusercontent.com/98641167/151656078-6b7c14dc-a7f8-4e23-b0ea-f89aab5b689f.png)

**Comment by OptimiliaStudios** [comment]
Highlighting related improvements are available from v1.1.33 onwards, plz try it out. In case you still are facing issues plz reactivate or create new issue.
