### ISSUE TITLE
Switching Dictionary Language

### ISSUE THREAD

**Issue by hikilinkuja** [OptimiliaStudios/AquileReader#78]
Greetings,

I've been having some **trouble changing the dictionary language from my native to english**.
I changed my computer time and location to US and even changed my microsoft account language that I use to log into Aquile.

The result is always the same:

![image](https://user-images.githubusercontent.com/99562120/153728862-12e1a6a6-e568-4183-8554-b945d6579e17.png)

However if I search for a word from my native language it will work.

![image](https://user-images.githubusercontent.com/99562120/153728931-6af6e67a-e47a-404a-b6b4-2070353f0c6e.png)

Could someone help me solve this issue?
Thanks.

**Comment by OptimiliaStudios** [comment]
@hikilinkuja with the latest app update (v1.1.15) we have added option to change the dictionary language. Now you can set the language explicitly to English and should get the right definitions.

How to do forcefully update - https://aquilereader.wordpress.com/how-to/#update
How to change dictionary language - https://aquilereader.wordpress.com/how-to/#dict-lang
