### ISSUE TITLE
Icons do not show when using light background

### ISSUE THREAD

**Issue by yunatea** [OptimiliaStudios/AquileReader#80]
When in the Home Menu, the icons on the left are in a light colour and can't be seen when using a light-coloured background.

**Comment by glientsc** [comment]
The same goes for me. I had to switch to a dark theme. Windows 11

**Comment by OptimiliaStudios** [comment]
@yunatea @glientsc with the latest app update (v1.1.15) we have tried fixing the issue, plz update the app and see if it helps in your case.
In case you are still facing the issue, plz share a screenshot of the issue.

https://aquilereader.wordpress.com/how-to/#update

**Comment by glientsc** [comment]
@OptimiliaStudios Thanks a lot, it works fine! Case closed.
