### ISSUE TITLE
canceled highlights cannot be highlighted again easily

### ISSUE THREAD

**Issue by deshuu** [OptimiliaStudios/AquileReader#81]
When I highlighted with a color A and canceled it, I cannot highlight it again with the same color A. Yet I could highlight it another color first, then change it to color A. Able to use, but complicated, lower the reading experience.

For another, the hotkey ctrl+c to copy is unavailable in the applicant. To me, hotkeys are more convenient than independent bottoms. Is there any way to open the hotkey using? 

Well thank you for your contribution, really love the readers!

**Comment by OptimiliaStudios** [comment]
Highlighting related improvements are available from v1.1.33 onwards, plz try it out.
