### ISSUE TITLE
will there be an android version or ios for this app?

### ISSUE THREAD

**Issue by RacimFethallah** [OptimiliaStudios/AquileReader#89]
This is one of the best apps i have ever seen i hope an android version or ios version will come to life, thanks for your works

**Comment by OptimiliaStudios** [comment]
Thanks for your feedback, we are actually working on an Android version of the app, it's currently in closed testing, if you are interested in trying out, plz share your Google Play Store login email Id, and will add you to the testing group.
You can reach out to us at optimilia.studios@gmail.com


https://play.google.com/store/apps/details?id=com.optimiliastudios.aquilereader
