### ISSUE TITLE
SUPPORT FOR PDF, CBR AND CBZ

### ISSUE THREAD

**Issue by rdanielb10** [OptimiliaStudios/AquileReader#93]
Hello friends. I'm using your app and it's great, but it has a little problem. Almost half of my books are PDFs, but your program does not support this format. In addition I also have several hundred comics and manga in CBR and CBZ format. Could you add support for these and more formats?

**Comment by OptimiliaStudios** [comment]
We have added PDF support from v1.1.53 of Windows and v1.1.54 of Android
