### ISSUE TITLE
Support Chinese language, thanks!

### ISSUE THREAD

**Issue by wangshanghai240** [OptimiliaStudios/AquileReader#97]

**Comment by OptimiliaStudios** [comment]
We have plans to add more languages in near future and would reach out to for translation help. If interested, please drop an email at optimilia.studios@gmail.com

**Comment by OptimiliaStudios** [comment]
Hi @wangshanghai240,
Aquile Reader is now ready for localization, you can contribute by following the details here - https://github.com/OptimiliaStudios/AquileReader/issues/111

**Comment by OptimiliaStudios** [comment]
Chinese language support has been added to the app.
